### ISSUE TITLE
React Admin + Flowise UI

### ISSUE THREAD

**Issue by ChakshuGautam** [BharatSahAIyak/flowise-ui#1]
## Context
[React Admin](https://github.com/marmelab/react-admin) a frontend Framework for building data-driven applications running on top of REST/GraphQL APIs, using TypeScript, React and Material Design.

[Flowise](https://github.com/FlowiseAI/Flowise) is a drag & drop UI to build your customized LLM flow.

## Description
This feature aims to integrate Flowise, a customizable drag & drop UI for creating LLM flows, directly into a React Admin application via a [custom route](https://marmelab.com/react-admin/CustomRoutes.html). 

The [current Flowise repository](https://github.com/BharatSahAIyak/flowise-ui) is a stripped-down version focusing solely on UI components, independent of any frontend framework. 

By embedding Flowise directly into React Admin using source code rather than an iframe, we expect to provide a seamless and cohesive user experience, ensuring that users can efficiently manage and interact with LLM flows within an existing React Admin dashboard.

## Goals
- [ ] Embed Flowise directly into React Admin using a custom route.
- [ ] Ensure the integration is seamless and consistent with the rest of the React Admin UI.
- [ ] Allow full interaction with Flowise’s features from within React Admin.
- [ ] Maintain high performance and responsiveness within the integrated application.
- [ ] Provide clear documentation on how to navigate and use the integrated Flowise features within React Admin.

## Expected Outcome
The final product will allow users to access and manage their LLM flows directly from a custom route within the React Admin interface. This integration should allow users to utilize all Flowise functionalities without needing to leave the React Admin environment.

## Acceptance Criteria
- [ ] Flowise is fully functional within React Admin without any performance degradation.
- [ ] Users can access all existing Flowise features from within React Admin.
- [ ] Documentation is provided, detailing the usage and benefits of the integration.

## Implementation Details
The integration will involve:
- Setting up a custom route in React Admin using its [Custom Routes](https://marmelab.com/react-admin/CustomRoutes.html) functionality.
- Importing the necessary Flowise components and ensuring they are compatible with React Admin's architecture.
- Testing for performance and compatibility issues between both systems.

## Mockups / Wireframes
Take a look at the [README](https://github.com/BharatSahAIyak/flowise-ui?tab=readme-ov-file#flowise-ui) to see Flowise UI

---

### Product
Bharat SahAIyak

### Organization Name:
SamagraX

### Tech Skills Needed:
React, TypeScript, Material Design, Experience with REST/GraphQL APIs

### Mentor(s)
@ChakshuGautam 

### Complexity
High

### Category
Feature, Integrations, UI/UX/Design

### Sub Category
Frontend, Configuration

**Comment by ChakshuGautam** [comment]
Share progress by raising a PR. Will assign post that.

**Comment by thekavikumar** [comment]
@ChakshuGautam sure, will do that.

can you please have a look at these too?
https://github.com/SamagraX-Stencil/ui-templates/pull/105

**Comment by thekavikumar** [comment]
@ChakshuGautam do we have to setup the react admin from scratch? because I can't find react admin package installed

**Comment by ChakshuGautam** [comment]
> @ChakshuGautam do we have to setup the react admin from scratch? because I can't find react admin package installed

Yes. Create a separate folder `admin` and add react-admin code.

**Comment by thekavikumar** [comment]
@ChakshuGautam Admin component requires a data provider, do we have a provider sir?
